blueprint:
  name: Living Room TV Virgin Media Input Selector v1.2
  description: >
    One script per Virgin channel. Powers on Virgin box and LG webOS TV,
    selects the baked-in Virgin channel via media_player.select_source,
    switches the TV to "Virgin(West Midlands) Set-Top Box", then sets Sonos volume.
    Channel is chosen once at creation from input_select.virgin_media_input_list.
  domain: script

  input:
    virgin_channel:
      name: Virgin channel/source (choose once)
      selector:
        state:
          entity_id: input_select.virgin_media_input_list

    volume_level:
      name: Sonos volume (0.00–1.00, per script)
      description: Target volume for media_player.living_room_sonos
      default: 0.35
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider

mode: restart
max_exceeded: silent

# -------- Global constants (edit here to affect ALL scripts using this blueprint) --------
variables:
  tv: media_player.lg_webos_smart_tv
  virgin: media_player.virgin_tv
  sonos: media_player.living_room_sonos

  # Timings
  tv_power_on_timeout: 10
  tv_source_list_timeout: 3
  tv_settle_delay: 3

  virgin_power_on_timeout: 5
  virgin_settle_delay: 1

  # Fixed values (baked into each script instance)
  desired_input: "Virgin(West Midlands) Set-Top Box"
  desired_channel: !input virgin_channel
  volume_level: !input volume_level

  # TV input matching helper (kept tolerant of case/spacing)
  tv_sources: "{{ state_attr(tv, 'source_list') or [] }}"
  tv_desired_norm: "{{ desired_input | lower | trim }}"
  tv_sources_norm: "{{ tv_sources | map('string') | map('lower') | list }}"
  tv_matched_source: >
    {% set d = tv_desired_norm %}
    {% set cand = tv_sources | list %}
    {% set norm = tv_sources_norm %}
    {% set idx = (norm.index(d) if d in norm else none) %}
    {% if idx is not none %}{{ cand[idx] }}
    {% else %}{{ desired_input }}
    {% endif %}

sequence:
  # 1) Power on Virgin if off
  - alias: Power on Virgin if off
    if:
      - condition: state
        entity_id: media_player.virgin_tv
        state: "off"
    then:
      - service: media_player.turn_on
        target:
          entity_id: media_player.virgin_tv
      - wait_template: "{{ states(virgin) not in ['off','unavailable','unknown'] }}"
        timeout: "{{ virgin_power_on_timeout }}"
      - delay:
          seconds: "{{ virgin_settle_delay }}"

  # 2) Select baked-in Virgin channel/source (no runtime matching)
  - alias: Select Virgin channel/source
    service: media_player.select_source
    target:
      entity_id: media_player.virgin_tv
    data:
      source: "{{ desired_channel }}"

  # 3) Power on TV if off
  - alias: Power on TV if off
    if:
      - condition: state
        entity_id: media_player.lg_webos_smart_tv
        state: "off"
    then:
      - service: media_player.turn_on
        target:
          entity_id: media_player.lg_webos_smart_tv
      - wait_template: "{{ states(tv) not in ['off','unavailable','unknown'] }}"
        timeout: "{{ tv_power_on_timeout }}"
      - delay:
          seconds: "{{ tv_settle_delay }}"

  # 4) (Optional) brief wait for TV sources (kept short; no channel matching)
  - alias: Optional short wait for TV sources
    wait_template: >
      {{ (state_attr(tv, 'source_list') or []) | count > 0
         or states(tv) not in ['off','unavailable','unknown'] }}
    timeout: "{{ tv_source_list_timeout }}"
    continue_on_timeout: true

  # 5) Switch TV to fixed input
  - alias: Switch TV to Virgin(West Midlands) Set-Top Box
    service: media_player.select_source
    target:
      entity_id: media_player.lg_webos_smart_tv
    data:
      source: "{{ tv_matched_source }}"

  # 6) Set Sonos Playbar volume
  - alias: Set Sonos volume
    service: media_player.volume_set
    target:
      entity_id: media_player.living_room_sonos
    data:
      volume_level: "{{ volume_level | float }}"

  - service: logbook.log
    data:
      name: "TV+Virgin+Sonos"
      message: >
        Virgin source (baked-in): '{{ desired_channel }}'.
        TV → '{{ tv_matched_source }}' (fixed input '{{ desired_input }}').
        Sonos volume: {{ (volume_level | float) | round(2) }}.
      entity_id: media_player.lg_webos_smart_tv
