blueprint:
  name: Room Thermostat OT Control v1.0.0
  description: >
    Adjust a Ramses_CC thermostat setpoint so that the room's operative temperature
    (OT / "feels like") matches the scheduled setpoint, taking into account occupancy
    time-of-day offsets. Uses ramses_cc.set_zone_mode with temporary_override and a
    timed duration. Scheduled setpoint is treated as the desired operative temperature.
  domain: automation

  input:
    thermostat_inputs:
      name: '# Thermostat / Schedule Inputs'
      collapsed: false
      input:
        thermostat:
          name: Target Thermostat (ramses_cc climate)
          selector:
            entity:
              integration: ramses_cc
              domain: climate

        scheduled_setpoint:
          name: Scheduled Setpoint Helper (Desired OT)
          description: >
            This value is treated as the desired operative ("feels like") temperature
            for the room. The blueprint will adjust the thermostat air setpoint so
            that measured OT tracks this value.
          selector:
            entity:
              domain: sensor
              device_class: temperature

    comfort_inputs:
      name: '# Comfort / Temperature Inputs'
      collapsed: false
      input:
        operative_temperature:
          name: Operative Temperature Sensor
          description: >
            Sensor providing the current operative / "feels like" temperature for this room.
          selector:
            entity:
              domain: sensor
              device_class: temperature

        mrt_temperature:
          name: Mean Radiant Temperature Sensor
          description: >
            Mean Radiant Temperature (MRT) for this room. Used for logging/diagnostics
            in this version.
          selector:
            entity:
              domain: sensor
              device_class: temperature

        min_thermostat_temp:
          name: Minimum Allowed Thermostat Setpoint
          description: >
            Lower bound for the thermostat air setpoint after OT correction and smoothing.
          selector:
            number:
              min: 5
              max: 20
              step: 0.5
          default: 10

        max_thermostat_temp:
          name: Maximum Allowed Thermostat Setpoint
          description: >
            Upper bound for the thermostat air setpoint after OT correction and smoothing.
          selector:
            number:
              min: 15
              max: 30
              step: 0.5
          default: 23

        smoothing_enabled:
          name: Enable Setpoint Smoothing
          description: >
            When enabled, blends the newly calculated OT-based setpoint with the current
            thermostat setpoint (60% new / 40% current) before rounding and clamping.
          default: true
          selector:
            boolean: {}

        run_interval_minutes:
          name: Run Interval (minutes)
          description: >
            How often this automation should take effect. It is evaluated every minute,
            but will only apply changes when the current minute is a multiple of this value.
          selector:
            number:
              min: 1
              max: 10
              step: 1
          default: 2

    occupancy_inputs:
      name: '# Occupancy Inputs'
      collapsed: false
      input:
        room_occupancy_sensor:
          name: Room Occupancy Sensor
          selector:
            entity:
              domain: binary_sensor

        unoccupied_duration:
          name: Unoccupied Duration (min)
          description: >
            Room must be continuously unoccupied for at least this many minutes before
            unoccupied offsets are applied.
          selector:
            number:
              min: 0
              max: 59
              step: 1
          default: 10

        reoccupied_duration:
          name: Reoccupied Duration (min)
          description: >
            Reserved for future use (kept for compatibility). Currently not used.
          selector:
            number:
              min: 0
              max: 5
              step: 1
