blueprint:
  name: Room Thermostat OT Control v1.2.0
  description: >
    Uses operative temperature (OT) and scheduled setpoint (as desired OT) to
    dynamically adjust the thermostat air temperature so the room "feels like"
    the scheduled value. MRT/OT come from input_numbers or temperature sensors.
    Scheduled setpoint comes from a template temperature sensor. Includes
    at_home_mode for weekend schedule override, occupancy & time-of-day offsets,
    smoothing, min/max clamp, and Ramses temporary_override.
    v1.0.9 adds: (1) correction gain (k) and (2) per-run setpoint change cap, and
    fixes occupancy offset doubling by halving it at the desired_OT stage.
    v1.1.1 adds: MRT/OT can now be input_number or temperature sensor entities.
    v1.2.0 adds: optional independent sensor compensation — when the Evohome zone
    sensor (TRV) reads higher than an independent room sensor, the final setpoint
    is boosted by the delta to compensate for TRV sensor overread.
  domain: automation

  input:
    thermostat_inputs:
      name: '# Thermostat / Schedule Inputs'
      collapsed: false
      input:
        thermostat:
          name: Target Thermostat (ramses_cc climate)
          selector:
            entity:
              integration: ramses_cc
              domain: climate

        scheduled_setpoint:
          name: Scheduled Setpoint Sensor (template sensor)
          description: >
            This *sensor* (not input_number) provides the desired operative
            temperature ("feels like") for the room.
            It must be a numeric temperature sensor (device_class = temperature).
          selector:
            entity:
              domain: sensor
              device_class: temperature

    comfort_inputs:
      name: '# Comfort / Temperature Inputs'
      collapsed: false
      input:
        operative_temperature:
          name: Operative Temperature (input_number or sensor)
          description: >
            The current operative temperature ("feels like") for the room.
            Can be an input_number helper or a temperature sensor.
          selector:
            entity:
              domain:
                - input_number
                - sensor
              device_class: temperature

        mrt_temperature:
          name: Mean Radiant Temperature (input_number or sensor)
          description: >
            The current mean radiant temperature for the room.
            Can be an input_number helper or a temperature sensor.
          selector:
            entity:
              domain:
                - input_number
                - sensor
              device_class: temperature

        min_thermostat_temp:
          name: Minimum Allowed Thermostat Setpoint
          selector:
            number:
              min: 5
              max: 20
              step: 0.5
          default: 10

        max_thermostat_temp:
          name: Maximum Allowed Thermostat Setpoint
          selector:
            number:
              min: 15
              max: 30
              step: 0.5
          default: 23

        smoothing_enabled:
          name: Enable Setpoint Smoothing
          description: >
            Smooths setpoint changes (60% new / 40% current). Helps avoid sudden jumps.
          selector:
            boolean: {}
          default: true

        run_interval_minutes:
          name: Run Interval (minutes)
          description: Runs every N minutes (1–10).
          selector:
            number:
              min: 1
              max: 10
              step: 1
          default: 2

        correction_gain:
          name: OT Correction Gain (k)
          description: >
            Proportion of OT error to apply. 1.0 = full correction (original behaviour).
            Typical: 0.25–0.6. Start around 0.4 (responsive rooms) or 0.5 (high MRT-lag rooms).
          selector:
            number:
              min: 0
              max: 1
              step: 0.05
          default: 0.4

        max_step_per_run:
          name: Max Setpoint Step per Run (°C)
          description: >
            Limits how much the thermostat setpoint can change each time the automation runs.
            Helps Evohome avoid large swings. Use 0.5°C to match Evohome steps.
            Set to 0 to disable rate limiting.
          selector:
            number:
              min: 0
              max: 2
              step: 0.5
          default: 0.5

    sensor_compensation_inputs:
      name: '# Independent Sensor Compensation'
      collapsed: true
      input:
        enable_sensor_compensation:
          name: Enable Sensor Compensation
          description: >
            When enabled, compares the Evohome zone temperature (TRV sensor) against
            an independent room temperature sensor. If the zone sensor reads higher
            than the independent sensor, the final setpoint is boosted by the
            difference to compensate for TRV sensor overread (e.g. radiant heat
            near the radiator warming the TRV). The boost naturally reduces as
            temperatures converge. Requires an independent sensor to be selected.
          selector:
            boolean: {}
          default: false

        independent_temp_sensor:
          name: Independent Temperature Sensor
          description: >
            An independent room temperature sensor (e.g. Govee H5075, Aqara, etc.)
            placed away from radiators for accurate room temperature reading.
            Only used when sensor compensation is enabled. Leave blank if not needed.
          default: ""
          selector:
            entity:
              domain: sensor
              device_class: temperature

        sensor_compensation_gain:
          name: Sensor Compensation Gain
          description: >
            Fraction of the sensor delta to apply. 1.0 = full delta, 0.5 = half.
            Lower values give gentler compensation. Start at 0.75.
          selector:
            number:
              min: 0.25
              max: 1.0
              step: 0.05
          default: 0.75

        max_sensor_compensation:
          name: Max Sensor Compensation (C)
          description: >
            Maximum additional setpoint boost from sensor compensation.
            Prevents runaway if the independent sensor goes stale or has a large offset.
          selector:
            number:
              min: 0.5
              max: 3.0
              step: 0.5
          default: 1.5

    occupancy_inputs:
      name: '# Occupancy Inputs'
      collapsed: false
      input:
        room_occupancy_sensor:
          name: Room Occupancy Sensor
          selector:
            entity:
              domain: binary_sensor

        unoccupied_duration:
          name: Unoccupied Duration (min)
          selector:
            number:
              min: 0
              max: 59
              step: 1
          default: 10

        reoccupied_duration:
          name: Reoccupied Duration (min)  # retained for compatibility
          selector:
            number:
              min: 0
              max: 5
              step: 1
          default: 2

        weekday_morning_offset:
          name: Weekday Morning Offset (06:30–12:00, Unoccupied)
          selector:
            number:
              min: -5
              max: 0
              step: 0.5
          default: -0.5

        weekday_afternoon_offset:
          name: Weekday Afternoon Offset (12:00–16:30, Unoccupied)
          selector:
            number:
              min: -5
              max: 0
              step: 0.5
          default: -0.5

        weekday_evening_offset:
          name: Weekday Evening Offset (16:30–22:00, Unoccupied)
          selector:
            number:
              min: -5
              max: 0
              step: 0.5
          default: -0.5

        weekend_morning_offset:
          name: Weekend Morning Offset (06:30–12:00, Unoccupied)
          selector:
            number:
              min: -5
              max: 0
              step: 0.5
          default: -0.5

        weekend_afternoon_offset:
          name: Weekend Afternoon Offset (12:00–16:30, Unoccupied)
          selector:
            number:
              min: -5
              max: 0
              step: 0.5
          default: -0.5

        weekend_evening_offset:
          name: Weekend Evening Offset (16:30–22:00, Unoccupied)
          selector:
            number:
              min: -5
              max: 0
              step: 0.5
          default: -0.5

    misc_inputs:
      name: '# Misc Inputs'
      collapsed: false
      input:
        at_home_mode:
          name: At Home Mode
          description: >
            When enabled, uses weekend schedule regardless of actual day.
            Use this when off work to follow weekend setpoints.
          selector:
            entity:
              domain: input_boolean

        automation_delay:
          name: Automation Delay (s)
          selector:
            number:
              min: 0
              max: 20
              step: 1
          default: 0

        override_duration_minutes:
          name: Temporary Override Duration (minutes)
          selector:
            number:
              min: 1
              max: 240
              step: 1
          default: 10

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  thermostat: !input thermostat
  scheduled_setpoint_var: !input scheduled_setpoint

  operative_temperature_var: !input operative_temperature
  mrt_temperature_var: !input mrt_temperature

  min_thermostat_temp: !input min_thermostat_temp
  max_thermostat_temp: !input max_thermostat_temp
  smoothing_enabled: !input smoothing_enabled
  run_interval_minutes: !input run_interval_minutes

  correction_gain: !input correction_gain
  max_step_per_run: !input max_step_per_run

  sensor_comp_enabled: !input enable_sensor_compensation
  independent_temp_sensor_var: !input independent_temp_sensor
  sensor_comp_gain: !input sensor_compensation_gain
  max_sensor_comp: !input max_sensor_compensation

  occupancy_sensor: !input room_occupancy_sensor
  unoccupied_duration: !input unoccupied_duration
  weekday_morning_offset: !input weekday_morning_offset
  weekday_afternoon_offset: !input weekday_afternoon_offset
  weekday_evening_offset: !input weekday_evening_offset
  weekend_morning_offset: !input weekend_morning_offset
  weekend_afternoon_offset: !input weekend_afternoon_offset
  weekend_evening_offset: !input weekend_evening_offset

  automation_delay: !input automation_delay
  override_duration_minutes: !input override_duration_minutes
  at_home_mode_var: !input at_home_mode

  thermostat_name: "{{ state_attr(thermostat, 'friendly_name') or thermostat }}"
  thermostat_currentsetpoint: "{{ state_attr(thermostat, 'temperature') | float(0) }}"
  evohome_zone_temp: "{{ state_attr(thermostat, 'current_temperature') | float(0) }}"

  scheduled_setpoint: "{{ states(scheduled_setpoint_var) | float(0) }}"
  operative_temp: "{{ states(operative_temperature_var) | float(0) }}"
  mrt_temp: "{{ states(mrt_temperature_var) | float(0) }}"

  at_home_mode_enabled: "{{ is_state(at_home_mode_var, 'on') }}"
  is_weekend: "{{ now().weekday() in [5, 6] or at_home_mode_enabled }}"

  time_period: >
    {% set m = now().hour*60 + now().minute %}
    {% if 390 <= m < 720 %}morning
    {% elif 720 <= m < 990 %}afternoon
    {% elif 990 <= m < 1320 %}evening
    {% else %}none{% endif %}

  unoccupied_offset: >
    {% if time_period == 'morning' %}
      {{ (is_weekend and weekend_morning_offset or weekday_morning_offset) }}
    {% elif time_period == 'afternoon' %}
      {{ (is_weekend and weekend_afternoon_offset or weekday_afternoon_offset) }}
    {% elif time_period == 'evening' %}
      {{ (is_weekend and weekend_evening_offset or weekday_evening_offset) }}
    {% else %}0{% endif %}

  is_unoccupied: >
    {% set s = occupancy_sensor %}
    {% if s and is_state(s, 'off') %}
      {{ ((as_timestamp(now()) - as_timestamp(states[s].last_changed)) / 60) >= unoccupied_duration }}
    {% else %}
      false
    {% endif %}
  is_unoccupied_bool: "{{ is_unoccupied | bool }}"

  _dur_h: "{{ override_duration_minutes // 60 }}"
  _dur_m: "{{ override_duration_minutes % 60 }}"

condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"

  - condition: template
    value_template: >
      {% set interval = run_interval_minutes | int %}
      {{ interval <= 1 or (now().minute % interval) == 0 }}

action:
  - condition: time
    before: "22:30:00"
    after: "06:30:00"

  - delay:
      seconds: "{{ automation_delay }}"

  - variables:
      # desired_ot is the "feels like" target. When unoccupied, we apply HALF the unoccupied_offset here
      # so that it is not doubled by the OT correction maths (Evohome setpoint impact equals unoccupied_offset).
      desired_ot: >
        {% if is_unoccupied_bool %}
          {{ scheduled_setpoint + (unoccupied_offset / 2) }}
        {% else %}
          {{ scheduled_setpoint }}
        {% endif %}

      # Gain-based OT correction:
      # raw_thermostat = desired_ot + k*(desired_ot - operative_temp)
      raw_thermostat: >
        {% set k = correction_gain | float(0.4) %}
        {{ desired_ot + (k * (desired_ot - operative_temp)) }}

      clamped_thermostat: >
        {% set t = raw_thermostat | float %}
        {% if t < min_thermostat_temp %}
          {{ min_thermostat_temp }}
        {% elif t > max_thermostat_temp %}
          {{ max_thermostat_temp }}
        {% else %}
          {{ t }}
        {% endif %}

      rounded_thermostat: >
        {{ ((clamped_thermostat * 2) | round(0) / 2) }}

      # Rate limit the change per run to avoid big swings (Evohome-friendly ramp).
      rate_limited_thermostat: >
        {% set t_new = rounded_thermostat | float %}
        {% set t_curr = thermostat_currentsetpoint | float(0) %}
        {% set step = max_step_per_run | float(0.5) %}

        {% if step <= 0 or t_curr <= 0 %}
          {{ t_new }}
        {% else %}
          {% set lo = t_curr - step %}
          {% set hi = t_curr + step %}
          {% if t_new < lo %}
            {{ lo }}
          {% elif t_new > hi %}
            {{ hi }}
          {% else %}
            {{ t_new }}
          {% endif %}
        {% endif %}

      smoothed_thermostat: >
        {% set t_new = rate_limited_thermostat | float %}
        {% set t_curr = thermostat_currentsetpoint | float %}

        {# Robustly fetch last_changed with full safety guards #}
        {% if thermostat in states and states[thermostat].last_changed is not none %}
          {% set last = states[thermostat].last_changed %}
        {% else %}
          {% set last = now() %}
        {% endif %}

        {# Now safe: last always resolves to a valid datetime object #}
        {% set age = (as_timestamp(now()) - as_timestamp(last)) | float(9999) %}

        {# Apply smoothing ONLY when:
           - smoothing is enabled
           - current setpoint is > 5°C
           - entity state has been stable for > 180 seconds
        #}
        {% if smoothing_enabled
              and t_curr > 5
              and age > 180 %}
          {{ (t_new * 0.6 + t_curr * 0.4) }}
        {% else %}
          {{ t_new }}
        {% endif %}

      final_thermostat: >
        {% set t = smoothed_thermostat | float %}
        {% if t < min_thermostat_temp %}
          {% set t = min_thermostat_temp %}
        {% elif t > max_thermostat_temp %}
          {% set t = max_thermostat_temp %}
        {% endif %}
        {{ ((t * 2) | round(0) / 2) }}

      # Independent sensor compensation: applied AFTER all OT/comfort calculations.
      # Compares the Evohome zone sensor (TRV) against an independent room sensor.
      # Only boosts when the zone sensor reads higher (positive delta).
      sensor_compensation: >
        {% if sensor_comp_enabled and independent_temp_sensor_var not in ['', None, 'unknown'] %}
          {% set ind_temp = states(independent_temp_sensor_var) | float(-999) %}
          {% set zone_temp = evohome_zone_temp | float(0) %}
          {% if ind_temp > 5 and zone_temp > 5 %}
            {% set delta = zone_temp - ind_temp %}
            {% if delta > 0 %}
              {{ [delta * (sensor_comp_gain | float(0.75)), max_sensor_comp | float(1.5)] | min }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}

      output_thermostat: >
        {% set t = (final_thermostat | float) + (sensor_compensation | float) %}
        {% if t < min_thermostat_temp %}
          {% set t = min_thermostat_temp %}
        {% elif t > max_thermostat_temp %}
          {% set t = max_thermostat_temp %}
        {% endif %}
        {{ ((t * 2) | round(0) / 2) }}

  - service: ramses_cc.set_zone_mode
    target:
      entity_id: !input thermostat
    data:
      mode: temporary_override
      setpoint: "{{ output_thermostat }}"
      duration:
        hours: "{{ _dur_h }}"
        minutes: "{{ _dur_m }}"
        seconds: 0

  - service: system_log.write
    data:
      level: warning
      message: >
        [Thermo {{ thermostat_name }}] OT CONTROL OVERRIDE → {{ output_thermostat }}°C
        (sched {{ scheduled_setpoint }}°C;
        desired_OT {{ desired_ot }}°C;
        OT {{ operative_temp }}°C;
        MRT {{ mrt_temp }}°C;
        k {{ correction_gain }};
        max_step_per_run {{ max_step_per_run }}°C;
        at_home_mode {{ at_home_mode_enabled }};
        unocc {{ is_unoccupied_bool }};
        unocc_offset {{ unoccupied_offset }}°C;
        smoothing {{ smoothing_enabled }};
        raw {{ raw_thermostat }}°C;
        rounded {{ rounded_thermostat }}°C;
        rate_limited {{ rate_limited_thermostat }}°C;
        smoothed {{ smoothed_thermostat }}°C;
        final {{ final_thermostat }}°C;
        sensor_comp {{ sensor_compensation }}°C;
        zone_temp {{ evohome_zone_temp }}°C;
        ind_temp {{ states(independent_temp_sensor_var) if independent_temp_sensor_var else 'n/a' }}°C;
        output {{ output_thermostat }}°C)
