blueprint:
  name: TV — Select Input v1.1
  description: >
    Switches a TV/media_player to the input named by an input_select helper.
    If the TV is off, it powers on, waits until responsive, then selects the input.
  domain: script
  input:
    tv:
      name: TV / Media Player
      selector:
        entity:
          domain: media_player

    input_helper:
      name: Input helper (input_select)
      description: The helper whose *current value* is the desired input/source.
      selector:
        entity:
          domain: input_select

    power_on_timeout:
      name: Power-on timeout (seconds)
      default: 90
      selector:
        number:
          min: 5
          max: 300
          unit_of_measurement: s
          mode: slider

    source_list_timeout:
      name: Source list availability timeout (seconds)
      description: Wait for TV to expose sources (if it does). Continues on timeout.
      default: 45
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: s
          mode: slider

    settle_delay:
      name: Extra settle delay after power-on (seconds)
      description: Some TVs need a short delay before accepting source changes.
      default: 3
      selector:
        number:
          min: 0
          max: 20
          unit_of_measurement: s
          mode: slider

mode: restart
max_exceeded: silent

variables:
  tv: !input tv
  input_helper: !input input_helper
  power_on_timeout: !input power_on_timeout
  source_list_timeout: !input source_list_timeout
  settle_delay: !input settle_delay

  desired_input: "{{ states(input_helper) | string }}"
  source_list: "{{ state_attr(tv, 'source_list') or [] }}"
  desired_norm: "{{ desired_input | lower | trim }}"
  source_list_norm: "{{ source_list | map('string') | map('lower') | list }}"

  matched_source: >
    {% set d = desired_norm %}
    {% set candidates = source_list | list %}
    {% set norm = source_list_norm %}
    {% set exact = (norm.index(d) if d in norm else none) %}
    {% if exact is not none %}
      {{ candidates[exact] }}
    {% else %}
      {% set starts = [] %}
      {% for i in range(norm|length) %}
        {% if norm[i].startswith(d) %}
          {% set _ = starts.append(i) %}
        {% endif %}
      {% endfor %}
      {% if starts %}
        {{ candidates[starts[0]] }}
      {% else %}
        {% set contains = [] %}
        {% for i in range(norm|length) %}
          {% if d in norm[i] %}
            {% set _ = contains.append(i) %}
          {% endif %}
        {% endfor %}
        {% if contains %}
          {{ candidates[contains[0]] }}
        {% else %}
          {{ desired_input }}  {# fall back to helper value even if not in list #}
        {% endif %}
      {% endif %}
    {% endif %}

sequence:
  - alias: Power on TV if off
    if:
      - condition: state
        entity_id: !input tv
        state: "off"
    then:
      - service: media_player.turn_on
        target:
          entity_id: !input tv

      - alias: Wait until TV becomes responsive
        wait_template: >
          {{ states(tv) not in ['off','unavailable','unknown'] }}
        timeout: "{{ power_on_timeout }}"

      - delay:
          seconds: "{{ settle_delay }}"

  - alias: Optionally wait for source_list to appear
    wait_template: >
      {{ (state_attr(tv, 'source_list') or []) | count > 0
         or states(tv) not in ['off','unavailable','unknown'] }}
    timeout: "{{ source_list_timeout }}"
    continue_on_timeout: true

  - alias: Switch input/source
    service: media_player.select_source
    target:
      entity_id: !input tv
    data:
      source: "{{ matched_source }}"

  - service: logbook.log
    data:
      name: "TV Input"
      message: >
        Helper '{{ input_helper }}' requested '{{ desired_input }}' → using '{{ matched_source }}' on {{ tv }}.
      entity_id: !input tv
